apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2gy0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0033-tenant/tkrw-pr712-0075-0033-app/devfile-sample-2gy0@sha256:f08ba9748c29a51791ebe62618c37e7ddb444cc796237591c20ac0fea46937dd
        name: my-nodejs
        resources: {}
status: {}
